# more on http://wiki.ros.org/navigation/Tutorials/RobotSetup

obstacle_range: 20       # obstacles put in map up to obstacle_range
raytrace_range: 25       # raytrace free space up to raytrace_range

lethal_cost_threshold: 10 # which value is a deadly obstacle

observation_sources: intel_realsense

intel_realsense: 
  data_type: 'PointCloud2'
  topic: /camera/depth/points_downsampled
  marking: true
  clearing: true
  min_obstacle_height: -100.0
  max_obstacle_height: 100.0
  observation_persistence: 0.1
  inf_is_valid: true
