submap_service: "/elevation_mapping/get_submap"
map_frame_id: "camera_link"  # odom   # Must be the same as the input elevation submap.     "odom"   "camera_link"
robot_frame_id: "camera_link"
min_update_rate: 1.5
map_center_x: 0.0
map_center_y: 0.0
map_length_x: 6.0
map_length_y: 6.0
footprint_yaw: 0.1
max_gap_width: 0.3
grid_map_to_initialize_traversability_map:
  enable: true
  grid_map_topic_name: initial_elevation_map
