input_sources:
  camera:
    type: pointcloud
    topic: "/camera/depth/color/points_downsampled"
    queue_size: 1
    publish_on_update: true
    sensor_processor: 
      ignore_points_above: .inf
      ignore_points_below: -.inf
      cutoff_min_depth: 0.2
      cutoff_max_depth: 3.25
      type: structured_light # https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8768489
      normal_factor_a: 0.000611
      normal_factor_b:  0.003587
      normal_factor_c: 0.3515
      normal_factor_d: 0
      normal_factor_e: 1
      lateral_factor: 0.01576 # approx 1 deg

# Written by Lefteris kotsonis.
# Modeling Realsense D435 Sensor Noise for Improved 3D Reconstruction and Tracking.
# sensor_processor:
#   type: structured_light
#   cutoff_min_depth: 0.2
#   cutoff_max_depth: 3.25
#   normal_factor_a: 0.000611
#   normal_factor_b:  0.003587
#   normal_factor_c: 0.3515
#   normal_factor_d: 0
#   normal_factor_e: 1
#   lateral_factor: 0.01576
