# more on http://wiki.ros.org/move_base

controller_frequency: 1
recovery_behavior_enabled: true
clearing_rotation_allowed: true

NavfnROS:
  allow_unknown: true # Specifies whether or not to allow navfn to create plans that traverse unknown space.
  default_tolerance: 0.2 # A tolerance on the goal point for the planner.

TebLocalPlannerROS:
  # Trajectory
  teb_autosize: True
  dt_ref: 0.2
  dt_hysteresis: 0.1
  global_plan_overwrite_orientation: false  
  max_global_plan_lookahead_dist: 1.2
  feasibility_check_no_poses: 10
  allow_init_with_backwards_motion: false
  global_plan_viapoint_sep: 0.5

  # Robot
  max_vel_x: 0.5
  max_vel_y: 0.2
  max_vel_x_backwards: 0.4
  max_vel_y_backwards: 0.1
  max_vel_theta: 1
  acc_lim_x: 0.02
  acc_lim_y: 0.01
  acc_lim_theta: 0.1
  
  use_proportional_saturation: true

  wheelbase: 0.0
  min_turning_radius: 0.1

  footprint: [[0.10, 0.10], [0.10, -0.10], [-0.10, -0.10], [-0.10, 0.10]]
  # footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
  #   type: "point"
  #   radius: 0.05 # for type "circular"
  #   line_start: [-0.1, 0.0] # for type "line"
  #   line_end: [0.3, 0.0] # for type "line"
  #   front_offset: 0.2 # for type "two_circles"
  #   front_radius: 0.2 # for type "two_circles"
  #   rear_offset: 0.2 # for type "two_circles"
  #   rear_radius: 0.2 # for type "two_circles"
  #   vertices: [[0.4, 0.4], [0.4, -0.4], [-0.4, -0.4], [-0.4, 0.4]]  # for type "polygon"

  # GoalTolerance
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  free_goal_vel: false
  complete_global_plan: false

  # Obstacles 
  min_obstacle_dist: 0.2
  inflation_dist: 0.025
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected: 50
  costmap_converter_plugin: ""
  costmap_converter_spin_thread: True
  costmap_converter_rate: 7

  # Optimization
  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: True
  optimization_verbose: false 
  penalty_epsilon: 0.1
  weight_max_vel_x: 2
  weight_max_vel_theta: 1
  weight_acc_lim_x: 1
  weight_acc_lim_theta: 1
  weight_kinematics_nh: 1000
  weight_kinematics_forward_drive: 1.0
  weight_kinematics_turning_radius: 0.5
  weight_optimaltime: 20
  weight_shortest_path: 1.0
  weight_obstacle: 50
  weight_viapoint: 0.01 # Increase to stick closer to global plan
  weight_dynamic_obstacle: 10 # not in use yet
  selection_alternative_time_cost: False # not in use yet
  


  # Homotopy Class Planner
  enable_homotopy_class_planning: false 
  enable_multithreading: True
  simple_exploration: True
  max_number_classes: 4
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_keypoint_offset: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: False
  delete_detours_backwards: True
  max_ratio_detours_duration_best_duration: 3.0
  
